# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'docker'
        repository: 'nizarmlaouihi/my-repo'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)

- stage: Deploy
  displayName: Deploy to AKS
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: KubernetesManifest@1
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: 'java-docker-test'
        namespace: 'aaaaa'
        strategy: 'canary'
        percentage: '0'
        manifests: |
          $(Pipeline.Workspace)/deployment.yaml
