trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: 'MySelfHostedPool'  # Ensure this matches your self-hosted agent pool name
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'docker'  # Name of your Docker Hub service connection
        repository: 'nizarmlaouihi/my-repo'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'

- stage: Deploy
  displayName: Deploy to AKS
  jobs:
  - job: Deploy
    displayName: Deploy to AKS
    pool:
      vmImage: 'ubuntu-latest'  # Microsoft-hosted agent image
    steps:
    - task: KubectlInstaller@0
      inputs:
        kubectlVersion: 'latest'

    - task: Kubernetes@1
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'java-docker-test'  # Ensure this matches your service connection name
        namespace: 'test'
        command: 'apply'
        secretType: 'dockerRegistry'
        containerRegistryType: 'Others'  # Use 'Others' for Docker Hub
        arguments: '-f ./deployment.yaml'  # Path to the deployment YAML at the root
